services:
  ml:
    build: ../ml
    container_name: tes-ml
    ports: ["8000:8000"]
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
  api:
    build: ../api
    container_name: tes-api
    depends_on: [ml]
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - ML_BASE_URL=http://ml:8000
      - SERVER_PORT=8080
    restart: unless-stopped
  web:
    build: ../web
    container_name: tes-web
    depends_on: [api]
    ports: ["5173:80"]
    environment:
      - VITE_API_BASE=http://localhost:8080
    restart: unless-stopped

