services:
  ml:
    build:
      context: ..                 # корень репо (.../nekoray/tes)
      dockerfile: ml/Dockerfile   # БЕЗ префикса "tes/"
    container_name: tes-ml
    working_dir: /app
    environment:
      - LOG_LEVEL=info
      - PYTHONPATH=/app
      - DATA_PATH=/app/data/got.yaml
    command: uvicorn ml.app:app --host 0.0.0.0 --port 8000
    ports:
      - "5006:8000"
    restart: unless-stopped
  api:
    build: ../api
    container_name: tes-api
    depends_on: [ml]
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - ML_BASE_URL=http://ml:8000
      - SERVER_PORT=8080
    restart: unless-stopped
  web:
    build: ../web
    container_name: tes-web
    depends_on: [api]
    ports: ["5173:80"]
    environment:
      - VITE_API_BASE=http://localhost:8080
    restart: unless-stopped

