server:
  port: ${API_PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

tes:
  ml:
    base-url: ${ML_BASE_URL:http://ml:5000}   # фикс опечатки: base-url

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
  pattern:
    correlation: "%X{requestId:-}"

cors:
  allowed-origins: ${ALLOWED_ORIGINS:https://tes.example.com}
  allowed-methods: "GET,POST,OPTIONS"
  allowed-headers: "*"