server:
  port: ${API_PORT:8080}

tes:
  ml:
    bas-url: ${ML_BASE_URL:http://ml:8000}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
  pattern:
    correlation: "%X{requestId:-}"

cors:
  allowed-origins: ${ALLOWED_ORIGINS:https://tes.example.com}
  allowed-methods: "GET,POST,OPTIONS"
  allowed-headers: "*"