server:
  port: ${SERVER_PORT:8080}
ml:
  baseUrl: ${ML_BASE_URL:http://localhost:8000}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha

