### Health
GET http://localhost:8080/actuator/health

### Recommendations (EN)
POST http://localhost:8080/recommendations
Content-Type: application/json

{
  "showId": "got",
  "targetSeason": 4,
  "immersion": 2,
  "locale": "en"
}
### Swagger UI
GET http://localhost:8080/swagger-ui.html

### OpenAPI JSON
GET http://localhost:8080/v3/api-docs